[package]
name = "fastping-rs"
version = "0.1.0"
authors = ["bparli <bparli@gmail.com>"]

[dependencies]
pnet = "0.21.0"
pnet_macros_support = "0.21.0"
env_logger = "0.5.13"
log = "0.4.5"
rand = "0.4"
